name="Mhuzaif"
age=18
height=1.79
is_student = True

print(name)
print(age)
print(height)
print(is_student)

print(type(name))
print(type(age))
print(type(height))
print(type(is_student))
print(age + 2)
print(height + 0.01)
print(age > 17)
name = input("What is your name? ")
print("Hello,", name)
user_age = int(input("How old are you? "))
print(type(user_age))
print("Next year you will be", user_age + 1)
print(10 + 3)
print(10 - 3)
print(10 * 3)
print(10 / 3)
print(10 // 3)
print(10 % 3)
print(10 ** 3)
print(10 == 10)
print(10 != 5)
print(10 > 5)
print(10 < 5)
print(10 >= 10)
print(10 <= 9)
print(age == 18)
print(age != 20)
print(age > 17 and age < 20)
print(age < 18 or age == 18)
age_text = str(age)
print(age_text)
print(type(age_text))
height_text = float("1.80")
print(height_text)
print(type(height_text))
age_text = str(age)
age_number = int("18")
height_number = float("1.8")
print(int("25") + 5)
print(float("2.5") + 1)
print(str(18) + " years old")
